import '@/styles/globals.css';
import { ReactNode } from "react";
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Front End Web Development',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className="min-h-screen bg-[#f6f5f9] font-sans antialiased">
                {children}
            </body>
        </html>
    );
}