import '@/styles/globals.css';
import { ReactNode } from "react";
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Front End Web Development',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode;
}) {
    return (
        <html lang="en">
        <body>{children}</body>
        </html>
    );
}